//
//  CountryRawData.swift
//  TravelAppProject
//
//  Created by 황인호 on 2023/10/08.
//

import Foundation

let countryRawData = """
GHA,가나,GHANA
GAB,가봉,GABON
GUY,가이아나,GUYANA
GMB,감비아,GAMBIA
GGY,건지 섬,GUERNSEY
GLP,과들루프,GUADELOUPE
GTM,과테말라,GUATEMALA
GUM,괌,GUAM
GRD,그레나다,GRENADA
GRC,그리스,GREECE
GRL,그린란드,GREENLAND
GIN,기니,GUINEA
GNB,기니비사우,GUINEA-BISSAU
NAM,나미비아,NAMIBIA
NRU,나우루,NAURU
NGA,나이지리아,NIGERIA
ATA,남극,ANTARCTICA
SSD,남수단,REPUBLIC OF SOUTH SUDAN
ZAF,남아프리카 공화국,SOUTH AFRICA
NLD,네덜란드,NETHERLANDS
ANT,네덜란드령 안틸레스,NETHERLANDS ANTILLES
NPL,네팔,NEPAL
NOR,노르웨이,NORWAY
NFK,노퍽 섬,NORFOLK ISLAND
NCL,누벨칼레도니,NEW CALEDONIA
NZL,뉴질랜드,NEW ZEALAND
NIU,니우에,NIUE
NER,니제르,NIGER
NIC,니카라과,NICARAGUA
KOR,대한민국,KOREA REPUBLIC OF
DNK,덴마크,DENMARK
DOM,도미니카 공화국,DOMINICAN REPUBLIC
DMA,도미니카 연방,DOMINICA
DEU,독일,GERMANY
TLS,동티모르,EAST TIMOR
LAO,라오스,LAO PEOPLE'S DEMOCRATIC REPUBLIC
LBR,라이베리아,LIBERIA
LVA,라트비아,LATVIA
RUS,러시아,RUSSIAN FEDERATION
LBN,레바논,LEBANON
LSO,레소토,LESOTHO
REU,레위니옹,REUNION
ROU,루마니아,ROMANIA
LUX,룩셈부르크,LUXEMBOURG
RWA,르완다,RWANDA
LBY,리비아,LIBYAN ARAB JAMAHIRIYA
LTU,리투아니아,LITHUANIA
LIE,리히텐슈타인,LIECHTENSTEIN
MDG,마다가스카르,MADAGASCAR
MTQ,마르티니크,MARTINIQUE
MHL,마셜 제도,MARSHALL ISLANDS
MYT,마요트,MAYOTTE
MAC,마카오,MACAU
MKD,마케도니아 공화국,REPUBLIC OF MACEDONIA
MWI,말라위,MALAWI
MYS,말레이시아,MALAYSIA
MLI,말리,MALI
IMN,맨 섬,ISLE OF MAN
MEX,멕시코,MEXICO
MCO,모나코,MONACO
MAR,모로코,MOROCCO
MUS,모리셔스,MAURITIUS
MRT,모리타니,MAURITANIA
MOZ,모잠비크,MOZAMBIQUE
MNE,몬테네그로,MONTENEGRO
MSR,몬트세랫,MONTSERRAT
MDA,몰도바, MOLDOVA REPUBLIC OF
MDV,몰디브,MALDIVES
MLT,몰타,MALTA
MNG,몽골,MONGOLIA
USA,미국,UNITED STATES
UMI,미국령 군소 제도,UNITED STATES MINOR OUTLYING ISLANDS
VIR,미국령 버진아일랜드,"VIRGIN ISLANDS, U.S."
MMR,미얀마,MYANMAR
FSM,미크로네시아 연방,MICRONESIA
VUT,바누아투,VANUATU
BHR,바레인,BAHRAIN
BRB,바베이도스,BARBADOS
VAT,바티칸 시국,VATICAN CITY STATE
BHS,바하마,BAHAMAS
BGD,방글라데시,BANGLADESH
BMU,버뮤다,BERMUDA
BEN,베냉,BENIN
VEN,베네수엘라,VENEZUELA
VNM,베트남,VIET NAM
BEL,벨기에,BELGIUM
BLR,벨라루스,BELARUS
BLZ,벨리즈,BELIZE
BIH,보스니아 헤르체고비나,BOSNIA HERCEGOVINA
BWA,보츠와나,BOTSWANA
BOL,볼리비아,BOLIVIA
BDI,부룬디,BURUNDI
BFA,부르키나파소,BURKINA FASO
BVT,부베 섬,BOUVET ISLAND
BTN,부탄,BHUTAN
MNP,북마리아나 제도,NORTHERN MARIANA ISLANDS
BGR,불가리아,BULGARIA
BRA,브라질,BRAZIL
BRN,브루나이,BRUNEI DARUSSALAM
WSM,사모아,SAMOA
SAU,사우디아라비아,SAUDI ARABIA
SGS,사우스조지아 사우스샌드위치 제도,SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS
SMR,산마리노,SAN MARINO
STP,상투메 프린시페,SAO TOME AND PRINCIPE
SPM,생피에르 미클롱,ST. PIERRE AND MIQUELON
ESH,서사하라,WESTERN SAHARA
SEN,세네갈,SENEGAL
SRB,세르비아,SERBIA
SYC,세이셸,SEYCHELLES
LCA,세인트루시아,SAINT LUCIA
VCT,세인트빈센트 그레나딘,SAINT VINCENT AND THE GRENADINES
KNA,세인트키츠 네비스,SAINT KITTS AND NEVIS
SHN,세인트헬레나,ST. HELENA
SOM,소말리아,SOMALIA
SLB,솔로몬 제도,SOLOMON ISLANDS
SDN,수단,SUDAN
SUR,수리남,SURINAME
LKA,스리랑카,SRI LANKA
SJM,스발바르 얀마옌,SVALBARD AND JAN MAYEN ISLANDS
SWZ,스와질란드,SWAZILAND
SWE,스웨덴,SWEDEN
CHE,스위스,SWITZERLAND
ESP,스페인,SPAIN
SVK,슬로바키아,SLOVAKIA
SVN,슬로베니아,SLOVENIA
SYR,시리아,SYRIAN ARAB REPUBLIC
SLE,시에라리온,SIERRA LEONE
SGP,싱가포르,SINGAPORE
ARE,아랍에미리트,UNITED ARAB EMIRATES
ABW,아루바,ARUBA
ARM,아르메니아,ARMENIA
ARG,아르헨티나,ARGENTINA
ASM,아메리칸사모아,AMERICAN SAMOA
ISL,아이슬란드,ICELAND
HTI,아이티,HAITI
IRL,아일랜드,IRELAND
AZE,아제르바이잔,AZERBAIJAN
AFG,아프가니스탄,AFGHANISTAN
AND,안도라,ANDORRA
ALB,알바니아,ALBANIA
DZA,알제리,ALGERIA
AGO,앙골라,ANGOLA
ATG,앤티가 바부다,ANTIGUA AND BARBUDA
AIA,앵귈라,ANGUILLA
ERI,에리트레아,ERITREA
EST,에스토니아,ESTONIA
ECU,에콰도르,ECUADOR
ETH,에티오피아,ETHIOPIA
SLV,엘살바도르,EL SALVADOR
GBR,영국,UNITED KINGDOM
YEM,예멘,YEMEN
OMN,오만,OMAN
AUS,오스트레일리아,AUSTRALIA
AUT,오스트리아,AUSTRIA
HND,온두라스,HONDURAS
ALA,올란드 제도,ALAND ISLANDS
WLF,왈리스 퓌튀나,WALLIS AND FUTUNA ISLANDS
JOR,요르단,JORDAN
UGA,우간다,UGANDA
URY,우루과이,URUGUAY
UZB,우즈베키스탄,UZBEKISTAN
UKR,우크라이나,UKRAINE
IRQ,이라크,IRAQ
IRN,이란,IRAN
ISR,이스라엘,ISRAEL
EGY,이집트,EGYPT
ITA,이탈리아,ITALY
IND,인도,INDIA
IDN,인도네시아,INDONESIA
JPN,일본,JAPAN
JAM,자메이카,JAMAICA
ZMB,잠비아,ZAMBIA
JEY,저지 섬,JERSEY
GNQ,적도 기니,EQUATORIAL GUINEA
PRK,조선민주주의인민공화국,"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"
GEO,조지아,GEORGIA
CAF,중앙아프리카 공화국,CENTRAL AFRICAN REPUBLIC
TWN,대만,TAIWAN
CHN,중화인민공화국,CHINA
DJI,지부티,DJIBOUTI
GIB,지브롤터,GIBRALTAR
ZWE,짐바브웨,ZIMBABWE
TCD,차드,CHAD
CZE,체코,CZECH REPUBLIC
CHL,칠레,CHILE
CMR,카메룬,CAMEROON
CPV,카보베르데,CAPE VERDE
KAZ,카자흐스탄,KAZAKHSTAN
QAT,카타르,QATAR
KHM,캄보디아,CAMBODIA
CAN,캐나다,CANADA
KEN,케냐,KENYA
CYM,케이맨 제도,CAYMAN ISLANDS
COM,코모로,COMOROS
CRI,코스타리카,COSTA RICA
CCK,코코스 제도,COCOS ISLANDS
CIV,코트디부아르,COTE D'IVOIRE
COL,콜롬비아,COLOMBIA
COG,콩고 공화국,CONGO
COD,콩고 민주 공화국,DEMOCRATIC REPUBLIC OF THE CONGO
CUB,쿠바,CUBA
KWT,쿠웨이트,KUWAIT
COK,쿡 제도,COOK ISLANDS
HRV,크로아티아,CROATIA
CXR,크리스마스 섬,CHRISTMAS ISLAND
KGZ,키르기스스탄,KYRGYZSTAN
KIR,키리바시,KIRIBATI
CYP,키프로스,CYPRUS
THA,타이,THAILAND
TJK,타지키스탄,TAJIKISTAN
TZA,탄자니아,"TANZANIA, UNITED REPUBLIC OF"
TCA,터크스 케이커스 제도,TURKS AND CAICOS ISLANDS
TUR,터키,TURKEY
TGO,토고,TOGO
TKL,토켈라우,TOKELAU
TON,통가,TONGA
TKM,투르크메니스탄,TURKMENISTAN
TUV,투발루,TUVALU
TUN,튀니지,TUNISIA
TTO,트리니다드 토바고,TRINIDAD AND TOBAGO
PAN,파나마,PANAMA
PRY,파라과이,PARAGUAY
PAK,파키스탄,PAKISTAN
PNG,파푸아 뉴기니,PAPUA NEW GUINEA
PLW,팔라우,PALAU
PSE,팔레스타인,PALESTINE
FRO,페로 제도,FAROE ISLANDS
PER,페루,PERU
PRT,포르투갈,PORTUGAL
FLK,포클랜드 제도,FALKLAND ISLANDS
POL,폴란드,POLAND
PRI,푸에르토리코,PUERTO RICO
FRA,프랑스,FRANCE
GUF,프랑스령 기아나,FRENCH GUIANA
ATF,프랑스령 남부와 남극 지역,FRENCH SOUTHERN TERRITORIES
PYF,프랑스령 폴리네시아,FRENCH POLYNESIA
FJI,피지,FIJI
FIN,핀란드,FINLAND
PHL,필리핀,PHILIPPINES
PCN,핏케언 제도,PITCAIRN
HMD,허드 맥도널드 제도,HEARD AND MC DONALD ISLANDS
HUN,헝가리,HUNGARY
HKG,홍콩,HONG KONG
"""
